apiVersion: v1
kind: Pod
metadata:
  name: maven-project
spec:
  containers:
  - name: maven
    image: maven:3.9.2-eclipse-temurin-11
    command:
    - /bin/cat
    tty: true
    volumeMounts:
    - name: shared-data
      mountPath: /home/jenkins/shared
  - name: kubectl
    image: alpine/k8s:1.27.1
    command:
    - /bin/cat
    tty: true
    volumeMounts:
    - name: shared-data
      mountPath: /home/jenkins/shared
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    - name: shared-data
      mountPath: /home/jenkins/shared
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: docker-regcred
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: shared-data
    emptyDir: {}
